title: Seema Simoliya
logo: /assets/img/logo.png
description: <p align="center">
  <a href="https://www.linkedin.com/in/seema-simoliya-a902a7199/">LinkedIn</a>
  <a href="https://github.com/seemasim">GitHub</a>
  
  
theme: jekyll-theme-minimal
